name: CI
'on':
  push:
    branches:
      - github*
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true
jobs:
  mainc-arch:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        container:
          - arch-0
        yp_ci_brew_install:
          - minimal
          - common
        yp_skip_sudo_bootstrap:
          - ''
          - 'true'
        yp_skip_brew_bootstrap:
          - ''
          - 'true'
    name: >-
      yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
      }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}:0.3.25'
      options: '--user yp:yp'
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      YP_LOG_BOOTSTRAP: true
      YP_PRINTENV_BOOTSTRAP: '${{ secrets.YP_PRINTENV_BOOTSTRAP }}'
      YP_TRANSCRYPT_PASSWORD: '${{ secrets.YP_TRANSCRYPT_PASSWORD }}'
      V: '${{ secrets.V }}'
      DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
      DOCKER_TOKEN: '${{ secrets.DOCKER_TOKEN }}'
      GITHUB_MATRIX_CONTAINER: '${{ matrix.container }}'
      GITHUB_MATRIX_YP_CI_BREW_INSTALL: '${{ matrix.yp_ci_brew_install }}'
      YP_SKIP_SUDO_BOOTSTRAP: '${{ matrix.yp_skip_sudo_bootstrap }}'
      YP_SKIP_BREW_BOOTSTRAP: '${{ matrix.yp_skip_brew_bootstrap }}'
      GITHUB_JOB_NAME: >-
        yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
        }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    steps:
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            bin/github-fix
            bin/github-checkout
      - shell: bash
        run: ./.ci.sh before_install
      - shell: bash
        run: ./.ci.sh install
      - shell: bash
        run: ./.ci.sh before_script
      - shell: bash
        run: ./.ci.sh script
      - if: failure()
        shell: bash
        run: ./.ci.sh after_failure || true
      - shell: bash
        run: ./.ci.sh after_success || true
      - if: always()
        shell: bash
        run: ./.ci.sh after_script || true
      - if: always()
        shell: bash
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_CHANNEL: cloud-ci
          YP_CI_STATUS: '${{ job.status }}'
        run: ./.ci.sh notifications || true
      - shell: bash
        run: ./.ci.sh before_deploy
      - shell: bash
        run: ./.ci.sh deploy
      - shell: bash
        run: ./.ci.sh after_deploy || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: >-
            yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
            }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
          path: |-
            yp-ci-echo-benchmark
            log.sh-session
          retention-days: 7
  mainc-alpine:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        container:
          - alpine-3.15
        yp_ci_brew_install:
          - minimal
          - common
        yp_skip_sudo_bootstrap:
          - ''
          - 'true'
        yp_skip_brew_bootstrap:
          - ''
          - 'true'
    name: >-
      yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
      }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}:0.3.25'
      options: '--user yp:yp'
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      YP_LOG_BOOTSTRAP: true
      YP_PRINTENV_BOOTSTRAP: '${{ secrets.YP_PRINTENV_BOOTSTRAP }}'
      YP_TRANSCRYPT_PASSWORD: '${{ secrets.YP_TRANSCRYPT_PASSWORD }}'
      V: '${{ secrets.V }}'
      DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
      DOCKER_TOKEN: '${{ secrets.DOCKER_TOKEN }}'
      GITHUB_MATRIX_CONTAINER: '${{ matrix.container }}'
      GITHUB_MATRIX_YP_CI_BREW_INSTALL: '${{ matrix.yp_ci_brew_install }}'
      YP_SKIP_SUDO_BOOTSTRAP: '${{ matrix.yp_skip_sudo_bootstrap }}'
      YP_SKIP_BREW_BOOTSTRAP: '${{ matrix.yp_skip_brew_bootstrap }}'
      GITHUB_JOB_NAME: >-
        yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
        }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    steps:
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            bin/github-fix
            bin/github-checkout
      - shell: bash
        run: ./.ci.sh before_install
      - shell: bash
        run: ./.ci.sh install
      - shell: bash
        run: ./.ci.sh before_script
      - shell: bash
        run: ./.ci.sh script
      - if: failure()
        shell: bash
        run: ./.ci.sh after_failure || true
      - shell: bash
        run: ./.ci.sh after_success || true
      - if: always()
        shell: bash
        run: ./.ci.sh after_script || true
      - if: always()
        shell: bash
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_CHANNEL: cloud-ci
          YP_CI_STATUS: '${{ job.status }}'
        run: ./.ci.sh notifications || true
      - shell: bash
        run: ./.ci.sh before_deploy
      - shell: bash
        run: ./.ci.sh deploy
      - shell: bash
        run: ./.ci.sh after_deploy || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: >-
            yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
            }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
          path: |-
            yp-ci-echo-benchmark
            log.sh-session
          retention-days: 7
  mainc-debian:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian-9
          - debian-10
        yp_ci_brew_install:
          - minimal
          - common
        yp_skip_sudo_bootstrap:
          - ''
          - 'true'
        yp_skip_brew_bootstrap:
          - ''
          - 'true'
    name: >-
      yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
      }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}:0.3.25'
      options: '--user yp:yp'
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      YP_LOG_BOOTSTRAP: true
      YP_PRINTENV_BOOTSTRAP: '${{ secrets.YP_PRINTENV_BOOTSTRAP }}'
      YP_TRANSCRYPT_PASSWORD: '${{ secrets.YP_TRANSCRYPT_PASSWORD }}'
      V: '${{ secrets.V }}'
      DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
      DOCKER_TOKEN: '${{ secrets.DOCKER_TOKEN }}'
      GITHUB_MATRIX_CONTAINER: '${{ matrix.container }}'
      GITHUB_MATRIX_YP_CI_BREW_INSTALL: '${{ matrix.yp_ci_brew_install }}'
      YP_SKIP_SUDO_BOOTSTRAP: '${{ matrix.yp_skip_sudo_bootstrap }}'
      YP_SKIP_BREW_BOOTSTRAP: '${{ matrix.yp_skip_brew_bootstrap }}'
      GITHUB_JOB_NAME: >-
        yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
        }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    steps:
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            bin/github-fix
            bin/github-checkout
      - shell: bash
        run: ./.ci.sh before_install
      - shell: bash
        run: ./.ci.sh install
      - shell: bash
        run: ./.ci.sh before_script
      - shell: bash
        run: ./.ci.sh script
      - if: failure()
        shell: bash
        run: ./.ci.sh after_failure || true
      - shell: bash
        run: ./.ci.sh after_success || true
      - if: always()
        shell: bash
        run: ./.ci.sh after_script || true
      - if: always()
        shell: bash
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_CHANNEL: cloud-ci
          YP_CI_STATUS: '${{ job.status }}'
        run: ./.ci.sh notifications || true
      - shell: bash
        run: ./.ci.sh before_deploy
      - shell: bash
        run: ./.ci.sh deploy
      - shell: bash
        run: ./.ci.sh after_deploy || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: >-
            yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
            }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
          path: |-
            yp-ci-echo-benchmark
            log.sh-session
          retention-days: 7
  mainc-ubuntu:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
        yp_ci_brew_install:
          - minimal
          - common
        yp_skip_sudo_bootstrap:
          - ''
          - 'true'
        yp_skip_brew_bootstrap:
          - ''
          - 'true'
    name: >-
      yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
      }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}:0.3.25'
      options: '--user yp:yp'
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      YP_LOG_BOOTSTRAP: true
      YP_PRINTENV_BOOTSTRAP: '${{ secrets.YP_PRINTENV_BOOTSTRAP }}'
      YP_TRANSCRYPT_PASSWORD: '${{ secrets.YP_TRANSCRYPT_PASSWORD }}'
      V: '${{ secrets.V }}'
      DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
      DOCKER_TOKEN: '${{ secrets.DOCKER_TOKEN }}'
      GITHUB_MATRIX_CONTAINER: '${{ matrix.container }}'
      GITHUB_MATRIX_YP_CI_BREW_INSTALL: '${{ matrix.yp_ci_brew_install }}'
      YP_SKIP_SUDO_BOOTSTRAP: '${{ matrix.yp_skip_sudo_bootstrap }}'
      YP_SKIP_BREW_BOOTSTRAP: '${{ matrix.yp_skip_brew_bootstrap }}'
      GITHUB_JOB_NAME: >-
        yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
        }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
    steps:
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            bin/github-fix
            bin/github-checkout
      - shell: bash
        run: ./.ci.sh before_install
      - shell: bash
        run: ./.ci.sh install
      - shell: bash
        run: ./.ci.sh before_script
      - shell: bash
        run: ./.ci.sh script
      - if: failure()
        shell: bash
        run: ./.ci.sh after_failure || true
      - shell: bash
        run: ./.ci.sh after_success || true
      - if: always()
        shell: bash
        run: ./.ci.sh after_script || true
      - if: always()
        shell: bash
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_CHANNEL: cloud-ci
          YP_CI_STATUS: '${{ job.status }}'
        run: ./.ci.sh notifications || true
      - shell: bash
        run: ./.ci.sh before_deploy
      - shell: bash
        run: ./.ci.sh deploy
      - shell: bash
        run: ./.ci.sh after_deploy || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: >-
            yp-${{ matrix.container }}-${{ matrix.yp_ci_brew_install }}-skipsudob${{ matrix.yp_skip_sudo_bootstrap
            }}-skipbrewb${{ matrix.yp_skip_brew_bootstrap }}
          path: |-
            yp-ci-echo-benchmark
            log.sh-session
          retention-days: 7
