name: CI
'on':
  push:
    branches:
      - github*
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true
jobs:
  test1:
    timeout-minutes: 30
    name: test1
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-ubuntu-20.04-minimal:latest'
      options: '--user yp:yp'
    steps:
      - shell: bash
        run: id -u; id -g
      - shell: bash
        run: echo "HOME=/home/yp" | sudo tee -a $GITHUB_ENV
      - shell: bash
        run: 'echo "WORKFLOW_DIR=$(dirname ${GITHUB_EVENT_PATH})" | sudo tee -a $GITHUB_ENV'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - shell: bash
        run: 'touch ~/test1; sudo touch /github/{home,workspace}/test1 ${WORKFLOW_DIR}/test1'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            id -u; id -g
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
            touch ~/test1-action; sudo touch /github/{home,workspace}/test1-action ${WORKFLOW_DIR}/test1-action
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace} || true'
  test2:
    timeout-minutes: 30
    name: test2
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-ubuntu-20.04-minimal:latest'
      options: '--user yp:yp'
    steps:
      - shell: bash
        run: id -u; id -g
      - shell: bash
        run: echo "HOME=/home/yp" | sudo tee -a $GITHUB_ENV
      - shell: bash
        run: 'echo "WORKFLOW_DIR=$(dirname ${GITHUB_EVENT_PATH})" | sudo tee -a $GITHUB_ENV'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - shell: bash
        run: 'touch ~/test2; sudo touch /github/{home,workspace}/test2 ${WORKFLOW_DIR}/test2'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            id -u; id -g
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
            touch ~/test2-action; sudo touch /github/{home,workspace}/test2-action ${WORKFLOW_DIR}/test2-action
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace} || true'
  test3:
    timeout-minutes: 30
    name: test3
    runs-on: ubuntu-latest
    container:
      image: 'ysoftwareab/yp-ubuntu-20.04-minimal:latest'
      options: '--user yp:yp'
    steps:
      - shell: bash
        run: id -u; id -g
      - shell: bash
        run: echo "HOME=/home/yp" | sudo tee -a $GITHUB_ENV
      - shell: bash
        run: 'echo "WORKFLOW_DIR=$(dirname ${GITHUB_EVENT_PATH})" | sudo tee -a $GITHUB_ENV'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - shell: bash
        run: 'touch ~/test3; sudo touch /github/{home,workspace}/test3 ${WORKFLOW_DIR}/test3'
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}'
      - uses: ysoftwareab/yplatform@master
        with:
          run: |-
            id -u; id -g
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
            touch ~/test3-action; sudo touch /github/{home,workspace}/test3-action ${WORKFLOW_DIR}/test3-action
            ls -la ${HOME}; ls -la /github/{home,workspace}; ls -la ${WORKFLOW_DIR}
      - shell: bash
        run: 'ls -la ${HOME}; ls -la /github/{home,workspace} || true'
    needs:
      - test1
      - test2
